<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageVersion>8.0.9635.60184</PackageVersion>
    <Authors>dazhong.yang</Authors>
    <Description>dazhong.yang</Description>
    <Copyright>dazhong.yang</Copyright>
    <PackageOutputPath>..</PackageOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WXEnvironment.Auth" Version="8.0.9489.46805" />
    <PackageReference Include="WXEnvironment.Common" Version="8.0.9489.42224" />
    <PackageReference Include="WXEnvironment.MongoDB" Version="8.0.9489.46375" />
  </ItemGroup>
</Project>